apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-xtb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lambda-xtb
  template:
    metadata:
      labels:
        app: lambda-xtb
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: lambda-xtb
          image: cerit.io/krupickm/lambda-xtb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: DATABASE_URL
              value: "sqlite:///data/lambda.db"
            - name: OMP_NUM_THREADS
              value: "4"
            - name: XDG_DATA_HOME
              value: "/tmp"
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              cpu: "4"
              memory: "2Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lambda-xtb-data
